# values.yaml
image:
  repository: 618465462717.dkr.ecr.ap-northeast-2.amazonaws.com/ekstest-app
  tag: v10

replicaCount: 2

service:
  name: ekstest-app
  type: LoadBalancer #ClusterIP
  port: 8080
